// <auto-generated />
using System;
using CryptoAgent.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace CryptoAgent.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoAgent.Domain.Entities.AgentDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("action");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("asset");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FundamentalVerdict")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fundamental_verdict");

                    b.Property<Guid[]>("NewsIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid[]")
                        .HasColumnName("news_ids")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("RawLlmOutput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_llm_output");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<decimal?>("SuggestedLeverage")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("suggested_leverage");

                    b.Property<string>("TechnicalVerdict")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("technical_verdict");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("Asset", "DecidedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_agent_decisions_asset_time");

                    b.ToTable("agent_decisions", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Domain.Entities.MarketNews", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("asset");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("headline");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<decimal?>("SentimentScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("sentiment_score");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.HasKey("Id");

                    b.HasIndex("Asset", "PublishedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_market_news_asset_published");

                    b.ToTable("market_news", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Domain.Entities.TechnicalSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("asset");

                    b.Property<decimal?>("Atr")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("atr");

                    b.Property<decimal?>("BbLower")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("bb_lower");

                    b.Property<decimal?>("BbMiddle")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("bb_middle");

                    b.Property<decimal?>("BbUpper")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("bb_upper");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("close_price");

                    b.Property<decimal?>("Ema20")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("ema_20");

                    b.Property<decimal?>("Ema200")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("ema_200");

                    b.Property<decimal?>("Ema50")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("ema_50");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("high_price");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("low_price");

                    b.Property<decimal?>("MacdHistogram")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("macd_histogram");

                    b.Property<decimal?>("MacdLine")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("macd_line");

                    b.Property<decimal?>("MacdSignal")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("macd_signal");

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("open_price");

                    b.Property<decimal?>("Rsi")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("rsi");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("timeframe");

                    b.Property<decimal>("Volume")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("Asset", "CapturedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_tech_snapshots_asset_time");

                    b.ToTable("technical_snapshots", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Domain.Entities.UserAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int[]>("AlertOnlyAssets")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("alert_only_assets");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("MinConfidenceThreshold")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasDefaultValue(0.7m)
                        .HasColumnName("min_confidence_threshold");

                    b.Property<string>("TelegramChatId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("telegram_chat_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("TelegramChatId")
                        .IsUnique()
                        .HasDatabaseName("idx_user_alerts_chat_id");

                    b.ToTable("user_alerts", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Domain.Entities.AgentDecision", b =>
                {
                    b.HasOne("CryptoAgent.Domain.Entities.TechnicalSnapshot", "Snapshot")
                        .WithMany("Decisions")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("CryptoAgent.Domain.Entities.TechnicalSnapshot", b =>
                {
                    b.Navigation("Decisions");
                });
#pragma warning restore 612, 618
        }
    }
}
